import {
    faLock,
    faLockOpen,
    faSuitcaseRolling,
    faMosque,
    faBars,
    faEnvelope,
    faEnvelopeOpen,
    faWifi,
    faQuestion,
    faInbox,
    faCommentAlt,
    faBell,
    faGlobe,
    faClipboard,
    faCalendarTimes,
    faCalendarAlt,
    faMobile,
    faClock,
    faDatabase,
    faCloudUploadAlt,
    faCloudDownloadAlt,
    faClipboardCheck,
    faCamera,
    faExclamationTriangle,
    faCheck,
    faDoorOpen,
    faPray,
    faStreetView,
    faChevronRight,
    faChevronDown,
    faStarAndCrescent,
    faSignOutAlt,
    faSearch,
    faTimes,
    faCompass,
    faPlus,
    faMinus,
    faArrowLeft,
    faArrowRight
 } from '@fortawesome/free-solid-svg-icons'

 import {
     faUserCircle,
     faPaperPlane
 } from '@fortawesome/free-regular-svg-icons'

import {
    faChrome,
    faFirefoxBrowser,
    faEdgeLegacy,
    faSafari,
    faLinux
} from '@fortawesome/free-brands-svg-icons'

export default [
    faLock,
    faLockOpen,
    faSuitcaseRolling,
    faMosque,
    faBars,
    faUserCircle,
    faEnvelope,
    faEnvelopeOpen,
    faPaperPlane,
    faWifi,
    faQuestion,
    faInbox,
    faCommentAlt,
    faBell,
    faChrome,
    faFirefoxBrowser,
    faEdgeLegacy,
    faSafari,
    faGlobe,
    faClipboard,
    faCalendarTimes,
    faCalendarAlt,
    faMobile,
    faClock,
    faDatabase,
    faCloudUploadAlt,
    faCloudDownloadAlt,
    faClipboardCheck,
    faCamera,
    faLinux,
    faExclamationTriangle,
    faCheck,
    faDoorOpen,
    faPray,
    faStreetView,
    faChevronRight,
    faChevronDown,
    faStarAndCrescent,
    faSignOutAlt,
    faSearch,
    faTimes,
    faCompass,
    faPlus,
    faMinus,
    faArrowLeft,
    faArrowRight
]